spring.application.name=rysolvia
stripe.secret.key=${STRIPE_KEY}
openai.secret.key=${OPENAI_KEY}


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://172.19.0.2:5432/mydb
spring.datasource.url=postgresql://matteolucia:pIiedkdyD82EUgjyL5hMExZZzcLKU87s@dpg-d7rfts3eo5us73c8q0vg-a/rysolviadatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gtp.model=gpt-5.4
#server.port=8082

server.port=${PORT:8080}

