spring.application.name=rysolvia
stripe.secret.key=${STRIPE_KEY}
openai.secret.key=${OPENAI_KEY}


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gpt.model=gpt-5.4
#server.port=8082

server.address=0.0.0.0
server.port=${PORT}
management.server.port=10000

server.forward-headers-strategy=framework
